version: 2

jobs:
  build:
    docker:
      - image: circleci/python:latest

    steps:
      - run: sudo apt-get update
      - run: sudo apt-get install -y g++ cmake make
      - run: cmake .
      - run: make
