version: 2

jobs:
  build:
    docker:
      - image: circleci/python:latest

    steps:
      - checkout
      - run: sudo apt-get update
      - run: sudo apt-get install -y g++ cmake make
      - run: cmake .
      - run: make

workflows:
  version: 2
  suite:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
